app/lab/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, ValidationError,\
    FloatField, IntegerField, SelectMultipleField, HiddenField
from flask_wtf.file import FileField, FileAllowed
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Length
from flask_pagedown.fields import PageDownField
from ..models import Clinic, Provider
from ..utils import Gender, CellType, ResultOption, FluidType, OrderName, ProviderDegree,\
    InstrumentType


class ProcedureForm(FlaskForm):
    """
    Form to add new standard operating provcedure
    for the lab
    """
    title = StringField('Title', validators=[DataRequired(), Length(0, 128)])
    procedure_content = PageDownField("Content goes here", validators=[DataRequired()])
    submit = SubmitField('Submit')


class MorphForm(FlaskForm):
    """
    Form to add Cells Morphology
    """
    cell_type = SelectField("Blood Cell Type", validators=[DataRequired()])
    morphology = StringField('Enter cell morphology', validators=[DataRequired()])
    options = SelectMultipleField("Morphology Options")
    submit = SubmitField('Submit')

    def __init__(self, *args, **kwargs):
        super(MorphForm, self).__init__(*args, **kwargs)
        self.cell_type.choices = [('', 'Select')]
        [self.cell_type.choices.append((each.name, each.value)) for each in CellType]
        self.options.choices = [('', 'Select')]
        [self.options.choices.append((each.value, each.name)) for each in ResultOption]


class ProviderForm(FlaskForm):
    """
    Form to add new Provider/Doctor/Nurses
    """
    f_name = StringField('First Name', validators=[DataRequired(), Length(1, 64)])
    m_name = StringField('Middle Name', validators=[DataRequired(), Length(1, 64)])
    l_name = StringField('Last Name', validators=[DataRequired(), Length(1, 64)])
    degree = SelectField('Provider Degree', validators=[DataRequired()])
    submit = SubmitField('Submit')

    def __init__(self, *args, **kwargs):
        super(ProviderForm, self).__init__(*args, **kwargs)
        self.degree.choices = [('', 'Select')]
        [self.degree.choices.append((choice.name, choice.value)) for choice in ProviderDegree]


class PatientForm(FlaskForm):
    """
    Form to add new Patient to database
    """
    f_name = StringField('First Name', validators=[DataRequired(), Length(1, 64)])
    m_name = StringField('Middle Name', validators=[DataRequired(), Length(1, 64)])
    l_name = StringField('Last Name', validators=[DataRequired(), Length(1, 64)])
    dob = DateField('Date of Birth', format='%Y-%m-%d', validators=[DataRequired()])
    gender = SelectField("Gender", validators=[DataRequired()])
    submit = SubmitField('Register')

    def __init__(self, *args, **kwargs):
        super(PatientForm, self).__init__(*args, **kwargs)
        self.gender.choices = [('', 'Select')]
        [self.gender.choices.append((choice.name, choice.value.capitalize())) for choice in Gender]


class ClinicForm(FlaskForm):
    """
    Form to add new Test ordering location
    """
    code_name = StringField('Clinic Code Name', validators=[DataRequired(), Length(1, 5)])
    name = StringField('Clinica Full Name', validators=[DataRequired(), Length(1, 128)])
    submit = SubmitField('Add Clinic')

    def validate_code_name(self, code_name):
        if code_name.data:
            name = Clinic.query.filter_by(clinic_code_name=code_name.data).first()
            if name:
                raise ValidationError('That clinc code is taken')


class UpdateClinicForm(FlaskForm):
    """
    Form to add new Test ordering location
    """
    code_name = StringField('Clinic Code Name', validators=[DataRequired(), Length(1, 5)])
    name = StringField('Clinica Full Name', validators=[DataRequired(), Length(1, 128)])
    submit = SubmitField('Update Clinic')

    def __init__(self, clinic, *args, **kwargs):
        super(UpdateClinicForm, self).__init__(*args, **kwargs)
        self.clinic = clinic

    def validate_code_name(self, field):
        if field.data != self.clinic.clinic_code_name and Clinic.query.filter_by(clinic_code_name=field.data).first():
            raise ValidationError('Clinic code name is already taken.')


class OrderForm(FlaskForm):
    """
    Form to add new requisiton for a lab test
    """
    location = SelectField('Order Location', coerce=int)
    provider = SelectField('Proivder', coerce=int)
    order_fluid_type = SelectField('Fluid Type', validators=[DataRequired(), Length(1, 128)])
    order_name = SelectField('Order Name', validators=[DataRequired(), Length(1, 128)])
    order_comment = StringField('Comment')
    submit = SubmitField('Add Order')

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.location.choices = [(clinic.id, clinic.clinic_code_name) for clinic in Clinic.query.order_by(Clinic.clinic_code_name).all()]
        self.provider.choices = [(provider.id, provider.pro_first_name + ' ' + provider.pro_last_name)
                                 for provider in Provider.query.order_by(Provider.pro_last_name).all()]
        self.order_fluid_type.choices = [(fluid.name, fluid.value.capitalize()) for fluid in FluidType]
        self.order_name.choices = [(order.name, order.value.upper()) for order in OrderName]


class CBDForm(FlaskForm):
    """
    Form to add some lab data and images from the smear.
    """
    wbc = FloatField('WBC count', validators=[DataRequired()])
    rbc = FloatField('RBC count', validators=[DataRequired()])
    hct = IntegerField('Hematocrit', validators=[DataRequired()])
    hgb = FloatField('Hemoglobin', validators=[DataRequired()])
    plt = IntegerField('Platelet', validators=[DataRequired()])
    instrument = SelectField('Instrument', validators=[DataRequired(), Length(1, 128)])
    images = FileField('Images', validators=[FileAllowed(['jpg'])])
    submit = SubmitField('Add Sample')

    def __init__(self, *args, **kwargs):
        super(CBDForm, self).__init__(*args, **kwargs)
        self.instrument.choices = [(ins.name, ins.value.upper()) for ins in InstrumentType]


class DiffForm(FlaskForm):
    """
    Form to finalize the diff
    """
    diff_value = HiddenField('Diff Value')
    submit = SubmitField("Confirm")

app/lab/__init__.py
from flask import Blueprint
lab = Blueprint('lab', __name__)
from . import routes

app/lab/routes.py
import bleach
import pytz
import tzlocal
from flask import redirect, render_template, url_for, flash, request, jsonify
from flask_login import login_required, current_user
from . import lab
from .forms import ProcedureForm, PatientForm, ClinicForm, OrderForm, MorphForm, CBDForm,\
    ProviderForm, DiffForm, UpdateClinicForm
from .. import db, database
from ..models import LabProcedure, Patient, Clinic, Order, CellImage, Morphology, BloodMorphology,\
    PathReview, Event, Sample, Provider, Smear
from ..utils import Privilege, privilege_required, admin_required, save_image, wbc_classification,\
    wbc_trial, smear_path_review, ResultOption, OrderEventType, wbc_exclusion, diff_pickle, \
    upload_file_to_s3

# add procedure


@lab.route('/procedures/add', methods=['GET', 'POST'])
@login_required
@privilege_required(Privilege.MODERATE)
def add_procedure():
    """
    Route to display form to add a
    Standard Operating Procedure for Lab
    """
    form = ProcedureForm()
    if form.validate_on_submit():
        procedure = LabProcedure(title=form.title.data,
                                 content=form.procedure_content.data,
                                 author=current_user._get_current_object())
        database.create(procedure)
        flash('Added procedure', 'success')
        return redirect(url_for('lab.all_procedures'))
    return render_template('lab/procedures/add_procedure.html', form=form)


@lab.route('/procedures')
@login_required
@privilege_required(Privilege.VIEW)
def all_procedures():
    """
    Route to display list of all SOP
    """
    procedures = LabProcedure.query.order_by(LabProcedure.timestamp.desc()).all()
    return render_template('lab/procedures/procedures.html', procedures=procedures)


@lab.route('/procedures/<int:id>')
@login_required
@privilege_required(Privilege.VIEW)
def procedure(id):
    """
    Route to display single SOP
    """
    procedure = LabProcedure.query.get_or_404(id)
    return render_template('lab/procedures/procedure.html', procedure=procedure)


@lab.route('/procedures/<int:id>/edit', methods=['GET', 'POST'])
@login_required
@privilege_required(Privilege.MODERATE)
def edit_procedure(id):
    """
    Route to edit a single procedure
    """
    procedure = LabProcedure.query.get_or_404(id)
    form = ProcedureForm()
    if form.validate_on_submit():
        procedure.title = form.title.data
        procedure.content = form.procedure_content.data
        database.update(procedure)
        flash('Procedure has been updated!', 'success')
        return redirect(url_for('lab.procedure', id=procedure.id))
    form.title.data = procedure.title
    form.procedure_content.data = procedure.content
    return render_template('lab/procedures/edit_procedure.html', procedure=procedure, form=form)


@lab.route('/clinics/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add_clinic():
    """
    Route to a new clinic location
    """
    form = ClinicForm()
    if form.validate_on_submit():
        clinic = Clinic(clinic_code_name=form.code_name.data,
                        clinic_full_name=form.name.data,
                        added_by=current_user.id)
        database.create(clinic)
        flash('Clinic has been added', 'success')
        return redirect(url_for('main.index'))
    return render_template('lab/clinics/add_clinic.html', form=form)


@lab.route('/clinics')
@login_required
@privilege_required(Privilege.VIEW)
def all_clinics():
    """
    Route to display all clinics
    """
    clinics = Clinic.query.all()
    return render_template('lab/clinics/clinics.html', clinics=clinics)


@lab.route('/clinics/<int:id>')
@login_required
@privilege_required(Privilege.VIEW)
def clinic(id):
    """
    Route to display single clinic detail information
    """
    clinic = Clinic.query.get_or_404(id)
    # Better way to do following #
    patients = db.session.query(Patient).join(Order, Clinic).filter(Clinic.id == clinic.id).distinct(Patient.id).all()
    return render_template('lab/clinics/clinic.html', clinic=clinic, patients=patients)


@lab.route('/clinics/<int:id>/edit', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_clinic(id):
    """
    Route to edit a clinic data
    """

    clinic = Clinic.query.get_or_404(id)
    form = UpdateClinicForm(clinic=clinic)
    if form.validate_on_submit():
        clinic.clinic_code_name = form.code_name.data
        clinic.clinic_full_name = form.name.data
        database.update(clinic)
        flash('clinic has been updated!', 'success')
        return redirect(url_for('lab.clinic', id=clinic.id))
    form.name.data = clinic.clinic_full_name
    form.code_name.data = clinic.clinic_code_name
    return render_template('lab/clinics/edit_clinic.html', clinic=clinic, form=form)


@lab.route('/providers/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add_provider():
    """
    Route to add new provider
    """
    form = ProviderForm()
    if form.validate_on_submit():
        provider = Provider(pro_first_name=form.f_name.data,
                            pro_last_name=form.l_name.data,
                            pro_middle_name=form.m_name.data,
                            degree=form.degree.data,
                            added_by=current_user.id)
        database.create(provider)
        flash('Provider has been added', 'success')
        return redirect(url_for('lab.all_providers'))
    return render_template('lab/providers/add_provider.html', form=form)


@lab.route('/providers')
@login_required
@privilege_required(Privilege.VIEW)
def all_providers():
    """
    Route to display all providers
    """
    providers = Provider.query.all()
    return render_template('lab/providers/providers.html', providers=providers)


@lab.route('/providers/<int:id>/edit', methods=['GET', 'POST'])
@login_required
@privilege_required(Privilege.CREATE)
def edit_provider(id):
    """
    Route to edit provider information
    """
    provider = Provider.query.get_or_404(id)
    form = ProviderForm()
    if form.validate_on_submit():
        provider.pro_first_name = form.f_name.data,
        provider.pro_last_name = form.l_name.data,
        provider.pro_middle_name = form.m_name.data,
        provider.degree = form.degree.data
        database.update(provider)
        flash('Provider data has been updated!', 'success')
        return redirect(url_for('lab.all_providers'))
    elif request.method == 'GET':
        form.f_name.data = provider.pro_first_name
        form.l_name.data = provider.pro_last_name
        form.m_name.data = provider.pro_middle_name
        form.degree.data = provider.degree.name
    return render_template('lab/providers/add_provider.html', provider=provider, form=form)


@lab.route('/patients/add', methods=['GET', 'POST'])
@login_required
@privilege_required(Privilege.CREATE)
def add_patient():
    """
    Route to add a new patient
    """
    form = PatientForm()
    if form.validate_on_submit():
        patient = Patient(pat_first_name=form.f_name.data,
                          pat_last_name=form.l_name.data,
                          pat_middle_name=form.m_name.data,
                          birth_date=form.dob.data,
                          gender=form.gender.data,
                          registered_by=current_user.id)
        database.create(patient)
        flash('Patient has been added', 'success')
        return redirect(url_for('lab.patient', id=patient.id))
    return render_template('lab/patients/add_patient.html', form=form)


@lab.route('/patients/<int:id>', methods=['GET', 'POST'])
@login_required
@privilege_required(Privilege.VIEW)
def patient(id):
    """
    Route to display single patient information
    """
    patient = Patient.query.get_or_404(id)
    age = patient.age()
    return render_template('lab/patients/patient.html', patient=patient,
                           age=age)


@lab.route('/patients')
@login_required
@privilege_required(Privilege.VIEW)
def all_patients():
    """
    Route to dispaly all patients
    Patients data will be pulled using
    ajax as a json object
    """
    return render_template('lab/patients/patients.html')


@lab.route('/patients/json')
@login_required
@privilege_required(Privilege.VIEW)
def json_patients():
    """
    Route to retrive patient data as JSON
    """
    patients = Patient.query.all()
    json_patients = jsonify({'data': [patient.to_json() for patient in patients]})
    return json_patients


@lab.route('/patients/<int:id>/edit', methods=['GET', 'POST'])
@login_required
@privilege_required(Privilege.CREATE)
def edit_patient(id):
    """
    Route to edit patient demographic data
    """
    patient = Patient.query.get_or_404(id)
    form = PatientForm()
    if form.validate_on_submit():
        patient.pat_first_name = form.f_name.data,
        patient.pat_middle_name = form.m_name.data,
        patient.pat_last_name = form.l_name.data,
        patient.birth_date = form.dob.data,
        patient.gender = form.gender.data
        database.update(patient)
        flash('Patient data has been updated!', 'success')
        return redirect(url_for('lab.patient', id=patient.id))
    elif request.method == 'GET':
        form.f_name.data = patient.pat_first_name
        form.m_name.data = patient.pat_middle_name
        form.l_name.data = patient.pat_last_name
        form.dob.data = patient.birth_date
        form.gender.data = patient.gender.name
    return render_template('lab/patients/edit_patient.html', patient=patient, form=form)


@lab.route('/patients/<int:id>/add_order', methods=['GET', 'POST'])
@login_required
@privilege_required(Privilege.CREATE)
def add_order(id):
    """
    Route to add new order to a patient
    """
    patient = Patient.query.get_or_404(id)
    form = OrderForm()
    if form.validate_on_submit():
        order = Order(donor=patient,
                      order_loc_id=form.location.data,
                      order_provider=form.provider.data,

app/templates/lab/patients/patient.html
{% extends "base.html" %}
{% block content %}
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Dashboard</a></li>
         <li class="breadcrumb-item"><a href="{{ url_for('lab.all_patients')}}">Patients</a></li>
         <li class="breadcrumb-item active" aria-current="page">{{patient.pat_first_name}} {{patient.pat_last_name}} </li>
      </ol>
   </nav>
   {% include '_flash.html' %}
   <div class="row">
      <div class="col-md-12">
         <div class="card">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
               <h6 class="m-0 font-weight-bold">Patient Profile</h6>
               <div>
                  {% if current_user.can(Privilege.CREATE) %}
                     <a class="btn btn-sm btn-primary" href="{{ url_for('lab.edit_patient', id=patient.id) }}" role="button"  title="Edit Patient Data"><i class="far fa-edit"></i></a>
                     <a class="btn btn-sm btn-success" href="{{ url_for('lab.add_order', id=patient.id) }}" role="button"  title="Add new order"><i class="fa fa-plus-circle"></i></a>
                  {% endif %}
               </div>
            </div>
            <div class="card-body text-center">               
               <div>
                  <span class="fa-stack fa-4x">
                     <i class="fa fa-circle fa-stack-2x"></i>
                     <i class="fa fa-user fa-stack-1x fa-inverse"></i>
                  </span>
                  <h2 class="mt-5">{{patient.pat_first_name}} {{patient.pat_last_name}}</h2>
                  <span>Patient ID: {{patient.id}}</span>                  
                  <div class="row justify-content-center mt-5 ">
                     <div class="col-xl-2 col-md-6 mb-4">
                        <div class="card h-100">
                           <div class="card-header bg-gold">
                              <div class="text-uppercase mb-1">age | dob</div>
                           </div>
                           <div class="card-body">
                              <div class="row justify-content-center">
                                 <div class="col mt-15 divide-line">
                                    <h6 class="text-muted">{{age}}</h6>
                                 </div>
                                 <div class="col m-t-15">
                                    <h6 class="text-muted">{{moment(patient.birth_date,'DD/MM/YYYY').format('MMM-Do-YYYY')}}</h6>                                    
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-2 col-md-6 mb-4">
                        <div class="card h-100">
                           <div class="card-header bg-gold">
                              <div class="text-uppercase mb-1">gender</div>
                           </div>
                           <div class="card-body">
                              <div class="row justify-content-center">
                                 <div class="col mr-2">                                    
                                    <h6 class="text-muted">{{ patient.gender.value.capitalize() }}</h6>
                                 </div>                                 
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-2 col-md-6 mb-4">
                        <div class="card h-100">
                           <div class="card-header bg-gold">
                              <div class="text-uppercase mb-1">First Visit</div>
                           </div>
                           <div class="card-body">
                              <div class="row justify-content-center">
                                 <div class="col mt-15 divide-line">
                                    <h6 class="text-muted">{{moment(patient.update_ts).fromNow()}}</h6>                                    
                                 </div>
                                 <div class="col m-t-15">
                                    <h6 class="text-muted">{{moment(patient.update_ts).format('LL')}}</h6>                                    
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-2 col-md-6 mb-4">
                        <div class="card h-100">
                           <div class="card-header bg-gold">
                              <div class="text-uppercase mb-1">Lab Order Count</div>
                           </div>
                           <div class="card-body">
                              <div class="row justify-content-center">
                                 <div class="col mr-2">                                    
                                    <h6 class="text-muted">{{patient.orders.count()}}</h6>
                                 </div>                                 
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="my-5">
                     <table class="table table-responsive-sm table-hover table-outline mb-0">
                        <thead class="thead-light">
                           <tr>
                              <th class="text-center">
                                 <i class="fas fa-hashtag"></i>
                              </th>
                              <th>Order ID</th>
                              <th class="text-center">Originate Date</th>
                              <th>Last Update</th>
                              <th>Clinic</th>
                              <th>Action</th>
                           </tr>
                        </thead>
                        <tbody>
                           {% for order in patient.orders %}
                              <tr>
                                 <td class="text-center">
                                    <div>
                                       <span>{{ loop.index }} </span>
                                    </div>
                                 </td>
                                 <td>
                                    <div>{{order.id}}</div>
                                 </td>
                                 {% with e = order.events.all() %}
                                 <td>
                                    <div>{{e[0].event_detail.name}}</div>
                                    <div class="small text-muted">{{moment(e[0].event_ts).format('YYYY-MMM-DD HH:mm')}}</div>
                                 </td>
                                 <td>
                                    <div>{{e[-1].event_detail.name}}</div>
                                    <div class="small text-muted">{{moment(e[-1].event_ts).format('YYYY-MMM-DD HH:mm')}}</div>
                                 </td>
                                 <td>
                                    <div class="text-center">
                                       <strong>{{order.ordering_location.clinic_full_name}}</strong>
                                    </div>
                                 </td>
                                 {% endwith%}
                                 <td>
                                    {% if order.samples.count() > 0 %}
                                       <a class="btn btn-sm btn-primary" href="{{url_for('lab.sample', id=order.samples[0].id)}}" role="button"  title="View Sample">
                                          <i class="fas fa-eye"></i>
                                       </a>
                                    {% else %}
                                       <a class="btn btn-sm btn-primary" href="{{url_for('lab.add_sample', id=order.id)}}" role="button"  title="Add Sample">
                                          <i class="fas fa-plus-circle"></i>
                                       </a>
                                    {% endif %}
                                 </td>
                              </tr>
                           {% endfor %}
                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
{% endblock content %}

app/templates/lab/patients/patients.html
{% extends "base.html" %}
{% block content %}
   
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Dashboard</a></li>
         <li class="breadcrumb-item active" aria-current="page">Patients</li>
      </ol>
   </nav>
   <div class="row">
      <div class="col-md-12">
         <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
               <h6 class="m-0 font-weight-bold">Patients</h6>
               <div>
                  {% if current_user.can(Privilege.CREATE) %}
                     <a class="btn btn-sm btn-primary" href="{{ url_for('lab.add_patient') }}" role="button"  title="Add Patient"><i class="fas fa-plus-square"></i></a>
                  {% endif %}
               </div>
            </div>
            <div class="card-body">
               <div class="table-responsive text-black">
                  <table class="table table-bordered display" id="dataTable" width="100%" cellspacing="0">
                     <thead>
                        <tr>
                           <th></th>
                           <th>Patient ID</th>
                           <th>Full Name</th>
                           <th>DOB</th>
                           <th>Age</th>
                           <th>Gender</th>
                           <th>Registration Date</th>
                        </tr>
                     </thead>
                     <tfoot>
                     <tr>
                        <th></th>
                        <th>Patient ID</th>
                        <th>Full Name</th>
                        <th>DOB</th>
                        <th>Age</th>
                        <th>Gender</th>
                        <th>Registration Date</th>
                     </tr>
                     </tfoot>
                     <tbody>                        
                     </tbody>
                  </table>
               </div>              
            </div>
         </div>
      </div>
   </div>
{% endblock content %}
{% block script %}
   <script src="{{url_for('static', filename='Packages/datatables/jquery.dataTables.min.js')}}"></script>
   <script src="{{url_for('static', filename='Packages/datatables/dataTables.bootstrap4.min.js')}}"></script>
   <script type="text/javascript">   
      $(document).ready(function() {
         $('#dataTable').DataTable( {
            ajax: "{{url_for('lab.json_patients')}}",
            columns: [            
               { className: 'text-center',
                  data: null, render: function ( data ) {
                  // button options for users
                  button_option =   '<a class="btn btn-sm btn-primary m-1" href="patients/'+data.id+'" class="editor_edit" title="View Patient Detail"><i class="fa fa-eye"></i> </a>'
                  {% if current_user.can(Privilege.CREATE) %}
                     button_option += '<a class="btn btn-sm btn-success m-1" href="patients/'+data.id+'/add_order" class="editor_edit" title="Add New Order"><i class="fa fa-plus-circle"></i> </a>'
                  {% endif %}
                  return button_option;
               } },
               { data: "id" },
               { data: "full_name" },
               { data: null, render:function(data){
                  return data.dob ;
               } },
               { data: "age" },
               { data: null, render:function(data){
                  return (data.gender);
               } },
               { data: null, render:function(data){
                  return moment(data.registered).format('MMM Do YYYY');
               } },              
               ]
            } );
         });
   </script>
{% endblock %}